import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import NextTopLoader from 'nextjs-toploader';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import SessionProvider from '@/components/layout/session';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang='en'>
      <body className={`${lato.className} antialiased`}>
        <NextTopLoader
          showSpinner={false}
          height={3}
          color='#DB4444'
          shadow='0'
        />
        <SessionProvider session={session}>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
