import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import NextTopLoader from 'nextjs-toploader';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lato.className} antialiased`}>
        <NextTopLoader showSpinner={false} height={2} color='#DB4444' />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
